name: Build and deploy the application to Koyeb

on:
  schedule:
    - cron: '50 8 * * *'
  push:
    branches:
      - 'main'

jobs:
  deploy:
    concurrency:
      group: "${{ github.ref_name }}"
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{ secrets.KOYEB_EXAMPLES_APPS_TOKEN }}"

      - name: Build and deploy the application
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: blabla
          git-builder: "docker"
          service-ports: "8000:http"
          service-routes: "/:8000"
          skip-cache: true
          service-regions: "was"
          service-instance-type: "free"
